### ISSUE TITLE
WebRTC stream doesn't load in latest Android App

### ISSUE THREAD

**Issue by rbray89** [jurriaan/janus-stream-custom-component#3]
Cross-linking from the Home assistant Android app issue: https://github.com/home-assistant/android/issues/2047

Seems the stream doesn't load. Web and older versions of the app are fine. My current assumption is that there is an issue in the Android app, but I am not familiar enough with either the WebRTC or Janus underpinnings to make that determination. Opening this issue primarily for documentation and exposure.

**Comment by rbray89** [comment]
So the issue is unfortunately this component it seems. The webRTC component works fine

**Comment by jurriaan** [comment]
Sorry for the delay. Found out what the issue was here, Janus does some checks for the browser version, which returns `null` since this commit I guess: https://github.com/home-assistant/android/commit/602b6b9be481abf00f03b809a8296673fbe30f85

I think that previously the chrome version was included, but since the user-agent is very simple now (does not include any info about the webview anymore) the underlying webrtcadapter library cannot determine the version properly and returns null.

This commit works around that: https://github.com/jurriaan/janus-stream-custom-component/commit/da1678e3f3809ef5399048eb8a60f08b2330fb71

It now works again on my Android device.
